apiVersion: v1
kind: Service
metadata:
  name: hello-flask-service
spec:
  selector:
    app: hello-flask
  ports:
  - protocol: "TCP"
    port: 9999
    targetPort: 5000
    nodePort: 31110
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
spec:
  selector:
    matchLabels:
      app: hello-flask
  replicas: 7
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image: hello-flask
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

